### ISSUE TITLE
[Meetup] Januari 2024

### ISSUE THREAD

**Issue by TomCools** [BeJUG/bejug.github.io#37]
## Task List

How about we start the year with an ALL QUICKIES evening!

- Kasper from TomTom had requested a slot
- Call for other speakers to do quickies

### Preparation

- [x] Find speaker(s)
- [x] Find location
- [x] Determine date
- [x] Announce event on Meetup.com
- [x] Promote on social media

### After the event

- [x] Send mail to attendees to wrap up
- [x] Shoutouts on social media
- [x] Share content (slides / video / images) if/when available
- [x] Promote next event (If available)

**Comment by lmagnette** [comment]
I've contacted the GDG of Mons and they're interested to host this event.

**Comment by TomCools** [comment]
Alternatively, if we do this event closer to the end of Januari, then we could get Charles Nutter (JRuby) to come give a talk.

**Comment by TomCools** [comment]
- Microsoft Innovation Centre: Mons
- 17th Januari

@TomCools : Check with Kasper
Idea: Maybe invite FOSDEM speakers to try out?
@TomCools : Check with Charles Nutter

**Comment by FDelporte** [comment]
FYI, I've a Fosdem talk that may need a tryout
"Experimenting with AI and LLM to make docs searchable through a chat application"

**Comment by octonato** [comment]
> FYI, I've a Fosdem talk that may need a tryout "Experimenting with AI and LLM to make docs searchable through a chat application"

This sound interesting. +1

**Comment by lmagnette** [comment]
The GDG Mons team contacted me because they encountered an issue with the original venue. Fortunately, they've found an alternative location. The event would still take place in Mons but at UMons instead of the MIC. They've proposed new dates: 18/01, 23/01, or 25/01. Would any of these dates work for you?

**Comment by TomCools** [comment]
I'd go for 23 or 25. Gives us a but more time to organize. @lmagnette

**Comment by lmagnette** [comment]
Any news for the date ?

**Comment by TomCools** [comment]
Hmm😅 i thought you were going to choose after I said "23 or 25" and you gave a thumbs up. 

But i'd say 25th now! 😅 could you provide the exact location and a logo for the host? I'll just post a "Quickies night" so we have multiple speakers.

**Comment by lmagnette** [comment]
Oh ok sorry 😅. Ok perfect for the 25. I contact them to get the rest of the info 😉

**Comment by lmagnette** [comment]
Here's the location and the logo.:
- Rue de Houdain 9, 7000 Mons. (Faculté polytechnique de Mons)
![Image](https://github.com/BeJUG/bejug.github.io/assets/6390187/daf40233-b94a-4fc2-9f1a-d203ce5c709f)

**Comment by TomCools** [comment]
Will make the card and draft meetup page tonight. 😊 any limit on attendees? (I'll put it by default on 40). And are food and drinks included?

**Comment by TomCools** [comment]
Social Card
![Social Card](https://github.com/BeJUG/bejug.github.io/assets/11362563/fe080ce5-1bf2-4b38-ae24-832a1cca6ec8)

**Comment by TomCools** [comment]
@lmagnette Added the draft meetup page already and made you a Host Loic! If you are willing to do the intro and such? Maybe I'll give a talk then since I don't want to host and present a talk. ;) https://www.meetup.com/belgian-java-user-group/events/298467787/

**Comment by TomCools** [comment]
@FDelporte and @octonato, can we count on you for a session? ;)

**Comment by FDelporte** [comment]
Count me in! Will try to make a bit a shorter version of Fosdem talk as a "rehearsel":
https://fosdem.org/2024/schedule/event/fosdem-2024-2379-experimenting-with-ai-and-llm-to-make-docs-searchable-through-a-chat-application/ --> a demo based on Langchain4J (+ JavaFX)

**Comment by octonato** [comment]
I can't promise anything at that moment. I don't even know yet if I be available on the 25th.

**Comment by EddieChoCho** [comment]
Hi, May I give a lightning talk about source code design of Spring distributed lock using Redis in this event?
https://hackmd.io/@GzkKWjbLTt6YExzxvjL9OA/H1fBMvJ63

**Comment by TomCools** [comment]
@EddieChoCho, if you can make it to Mons, you are in. 😊

**Comment by TomCools** [comment]
!New card for promo](https://github.com/BeJUG/bejug.github.io/assets/11362563/33db277b-061a-4912-b9ff-16eb5494d6a4)

**Comment by TomCools** [comment]
Promoted at:

Mastodon: https://foojay.social/@BeJUG/111738975758520645

**Comment by lmagnette** [comment]
I've sent the links to the GDG so they can reshare and hopefully boost it.
